# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on: ['push', 'pull_request']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv
        pipenv install --dev
    - uses: PennyDreadfulMTG/setup-linters@main
    - name: Test with mypy
      run: |
        pipenv run mypy --install-types --non-interactive .
    - name: Test with Flake8
      run: |
        pipenv run flake8 .
    - name: Test with pytest
      run: |
        pipenv run pytest
